services:
  mongodb:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: scoutlens_admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  etl:
    container_name: etl-script
    build: scoutlens-etl
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=scoutlens
      - MONGO_COLLECTION=players
      - MONGO_USER=scoutlens_admin
      - MONGO_PASSWORD=password
    links:
      - mongodb

volumes:
  mongodb_data:
    driver: local
